aliases: []
creation_timestamp: 1729783625273
current_stage: None
description: null
last_updated_timestamp: 1729783625273
name: ElasticModel
run_id: a6c765ae67f549b0a96cfa8c6a6e88a4
run_link: null
source: mlflow-artifacts:/9ae8f79f3cee4c0780d8fb71193c635d/a6c765ae67f549b0a96cfa8c6a6e88a4/artifacts/model
status: READY
status_message: null
storage_location: mlflow-artifacts:/9ae8f79f3cee4c0780d8fb71193c635d/a6c765ae67f549b0a96cfa8c6a6e88a4/artifacts/model
user_id: null
version: 6
