artifact_location: file:///c:/Users/ambig/jupiter_notebook/MLOPS/datascienceproject/fb2f95b034bede9a12064d51b3918656290ea18c/0
creation_time: 1729770470359
experiment_id: '0'
last_update_time: 1729770470359
lifecycle_stage: active
name: Default
